## 数据库的连接新
#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.56.100:3306/mall-oms
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.56.100:8848
#  application:
#    name: mall-order
#
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto # 主键自增
#
#server:
#  port: 8030
#
#user:
#  userName: zhangsan
#  age: 18
